---
libertysecure: 
  version: 1.0.0
  required: false
  requirements: 
    liberty: 
      min: 2.1.5
  description: >
    This package secures liberty content
    list queries when using custom content
    permissions. This package is required to
    use custom content permissions.
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html
  homeable: false
  tables: 
    liberty_secure_permissions_map: |
      
      perm_name C(30) PRIMARY,
      perm_type C(30) PRIMARY,
      content_type_guid C(32) PRIMARY
      CONSTRAINT ', CONSTRAINT `libertysecure_perm_name_ref` FOREIGN KEY (`perm_name`) REFERENCES `users_permissions`( `perm_name` )
      , CONSTRAINT `libertysecure_content_type_ref` FOREIGN KEY (`content_type_guid`) REFERENCES `liberty_content_types`( `content_type_guid` )'
      
